### ISSUE TITLE
Controller 에서 204 상태 코드 반환시 데이터베이스 Commit이 수행되지 않음

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN-backend-service#4]

**Comment by YooYoungmo** [comment]
Echo 프레임워크 문제로
Controller 에서 HTTP Status Code 204(No Content)를 반환할 때는 아래와 같이 반환해야 한다.
```go
return ctx.NoContent(http.StatusNoContent)
```

위와 같이 하면 Commit 이 정상적으로 수행된다.
자세한 내용은 아래 링크 참조

https://echo.labstack.com/guide/response/

**Comment by YooYoungmo** [comment]
이슈를 Close 합니다.

**Comment by ahnyounghoe** [comment]
이건 뭐지? 응답은 했는데, DBMS 열어 둬서 메모리 낭비하는 일을 막아주는 방법인가?

**Comment by YooYoungmo** [comment]
@ahnyounghoe  better ADMIN 은 웹 프레임워크로 [Echo](https://echo.labstack.com/) 를 사용하고 있습니다.

Echo 에서는 [Middleware](https://echo.labstack.com/middleware/) 라는 것을 제공합니다.
Middleware를 사용하면 인터셉터와 같이 HTTP Reqeust 와 Response 를 가로채서 부가적인 로직을 추가하는 것이 가능합니다.

데이터베이스 트랜잭션을 개발자가 직접 다루지 않도록 하기 위해 Echo Middleware를 사용하고 있습니다.
HTTP Request 가 오면 데이터베이스 트랜잭션을 시작하고 
개발자가 작성하는 Controller에서 반환하는 값에 따라 
HTTP Response HTTP Status Code가  5XX(Internal Server Error) 라면 데이터베이스 트랜잭션을 Rollback하고 그렇지 않으면 Commit 합니다.

그런데 Controller 에서 아래와 같이 HTTP Status Code 204(No Content)을 반환하면 트랜잭션이 Commit 되지 않고 Rollback 되는 현상이 발생했습니다.
```golang
return c.JSON(http.StatusNoContent, nil)
```

Echo 문서를 확인해 보니 HTTP Status Code 204(No Content)를 반환할 때에는 아래와 같이 해야 정상적으로 작동한다는 것을 확인한 것이었습니다.
```golang
return ctx.NoContent(http.StatusNoContent)
```

**Comment by ahnyounghoe** [comment]
@YooYoungmo 땡큐. 에코 미들웨어 형태로 트랜젝션 관리를 하는군
