### ISSUE TITLE
Refresh 토큰 쿠키 저장시 만료 시간 추가 지정한다.

### ISSUE THREAD

**Issue by YooYoungmo** [bettercode-oss/better-ADMIN-backend-service#54]
# 문제
쿠키 Refresh 토큰에 만료 시간을 지정하지 않아 브라우저를 종료하면 다시 로그인해야 한다.

# 완료 목표
Refresh 토큰 쿠키 저장시 만료 시간 추가 지정한다.

**Comment by ahnyounghoe** [comment]
@YooYoungmo 이 기능과 관련하여 어떠한 설정 값이 있나?

**Comment by ahnyounghoe** [comment]
@YooYoungmo 문제가 아래와 같이 기술되어 있는데
> 쿠키 Refresh 토큰에 만료 시간을 지정하지 않아 브라우저를 종료하면 다시 로그인해야 한다

이 기능 추가후에는
브라우저를 종료해도 다시 로그인 할 필요가 없어지는 것인가?

**Comment by YooYoungmo** [comment]
@ahnyounghoe 

> 이 기능과 관련하여 어떠한 설정 값이 있나?

지금은 토큰 만료 시간은 하드코딩 되어 있는 상태 입니다. 별도로 config 파일로 뺄 예정입니다.

> 브라우저를 종료해도 다시 로그인 할 필요가 없어지는 것인가?

예. 맞습니다. 기존에는 쿠키 보관이 브라우저 Session 이었기 때문에 브라우저를 종료하거나 하면 다시 로그인해야 했는데요.
지금은 브라우저가 종료되더라도 쿠키에 토큰이 남아 있기 때문에 다시 로그인할 필요가 없습니다.
